config/routes.rb
Icampus::Application.routes.draw do

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :sessions
  resources :password_resets
  resources :users do
    resources :newsfeeds do
      collection { post :sort }
    end
    resources :photosfeeds do
      collection { post :sort }
    end
    resources :videosfeeds do
      collection { post :sort }
    end
    resources :eventsfeeds do
      collection { post :sort }
    end
    resource :directory
    resource :athletic
    resource :library_worldcat
    resources :centers
    resources :ios_main_icons
    resources :ios_feature_icons
    resources :ios_backgrounds
    resource :ios_topbar
    resources :android_main_icons
    resources :android_feature_icons
    resources :android_backgrounds
    resource :android_topbar
    resources :mobile_web_feature_icons
    resources :mobile_web_logos
    resource :mobile_web_topbar
    resource :apple_developer
    resource :android_profile
    resources :testers
    resource :project_info_page
    resource :support_email
    resource :cname
    resource :info_appstore
    member do
      get 'change_password'
      put 'change_password_update'
    end
    collection do
      get 'tab_feat'
      get 'tab_graph'
      get 'tab_dist'
      get 'tab_rel'
    end
  end

  resources :centers do
    resources :emergency_phones
    resources :emergency_contacts
    resources :places
    resources :library_locations do
      resources :library_hours
      resources :library_contacts
    end
  end

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :users do
      resources :centers
      member do
        get 'tab_feat'
        get 'tab_graph'
        get 'tab_dist'
        get 'tab_rel'
      end
    end
  end

  root :to => 'users#index'

end

app/models/library_contact.rb
class LibraryContact < ActiveRecord::Base
	belongs_to :library_location
	
	attr_accessible :title, :phone, :email, :library_location_id
	validates_presence_of :title, :phone, :email, :library_location_id
end

app/controllers/library_contacts_controller.rb
class LibraryContactsController < ApplicationController

  before_filter :load_user_center
  before_filter :load_library_location
  # GET /library_contacts
  # GET /library_contacts.json
  def index
    @library_contacts = @library_location.library_contacts.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @library_contacts }
    end
  end

  # GET /library_contacts/1
  # GET /library_contacts/1.json
  def show
    @library_contact = @library_location.library_contacts.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @library_contact }
    end
  end

  # GET /library_contacts/new
  # GET /library_contacts/new.json
  def new
    @library_contact = @library_location.library_contacts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @library_contact }
    end
  end

  # GET /library_contacts/1/edit
  def edit
    @library_contact = @library_location.library_contacts.find(params[:id])
  end

  # POST /library_contacts
  # POST /library_contacts.json
  def create
    @library_contact = @library_location.library_contacts.new(params[:library_contact])

    respond_to do |format|
      if @library_contact.save
        format.html { redirect_to center_library_location_path(@center, @library_location), :flash => { success: 'Library contact was successfully created.' }}
        format.json { render json: @library_contact, status: :created, location: center_library_location_path(@center, @library_location) }
      else
        format.html { render action: "new" }
        format.json { render json: @library_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /library_contacts/1
  # PUT /library_contacts/1.json
  def update
    @library_contact = @library_location.library_contacts.find(params[:id])

    respond_to do |format|
      if @library_contact.update_attributes(params[:library_contact])
        format.html { redirect_to center_library_location_path(@center, @library_location), :flash => { success: 'Library contact was successfully updated.' }}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @library_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /library_contacts/1
  # DELETE /library_contacts/1.json
  def destroy
    @library_contact = @library_location.library_contacts.find(params[:id])
    @library_contact.destroy

    respond_to do |format|
      format.html { redirect_to center_library_location_path(@center, @library_location) }
      format.json { head :no_content }
    end
  end
end

app/helpers/library_contacts_helper.rb
module LibraryContactsHelper
end

app/views/library_contacts/_contact.html.erb
<% @library_location.library_contacts.each do |library_contact| %>
  <div class="row-fluid show-lib-hc">
      <div class="span1"><div class="cms-icon icon-small cms-book-small"></div></div>
      <div class="span3 hc-left">
        <h4><%= library_contact.title %></h4>
      </div>
      <div class="span2 hc-middle">
        <p><%= library_contact.phone %></p>
      </div>
      <div class="span3 hc-middle">
        <p><%= library_contact.email %></p>
      </div>
      <div class="span3 hc-controls">
        <div class="current-actions-wrap">
          <div class="current-actions">
          <div class="btn-group">
          <%= link_to 'Edit', edit_center_library_location_library_contact_path(@center, @library_location, library_contact), :class => 'btn btn-small' %>
          <%= link_to 'Delete', [@center, @library_location, library_contact], :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-small' %>
          </div>
          </div>
        </div>
      </div>
  </div>
<% end %>

app/views/library_contacts/_form.html.erb
<%= form_for([@center, @library_location, @library_contact], :html => { :class => "form-inline" }) do |f| %>
  <% if @library_contact.errors.any? %>
    <div class ="alert alert-error">
      <b><%= pluralize(@library_contact.errors.count, "error") %> caught: </b>
      <% @library_contact.errors.full_messages.each do |msg| %>
        <%= msg %>
      <% end %>
      <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
  <% end %>

  <div class="row-fluid">
    <div class="field inline-field span3 pad">
      <%= f.text_field :title, :placeholder => "Title", :class => 'fullw' %>
    </div>
    <div class="field inline-field span3 pad">
      <%= f.text_field :phone, :placeholder => "Phone", :class => 'fullw' %>
    </div>
    <div class="field inline-field span3 pad">
      <%= f.text_field :email, :placeholder => "E-Mail", :class => 'fullw' %>
    </div>
    <!-- f.hidden_field :library_location_id, :type => :number_field --> 
    <% if @library_contact.new_record? %>
     <div class="actions inline-field span3">
      <%= button_tag(:type => 'submit', class: "btn btn-primary btn-large pull-right") do %>
       <i class="icon-plus-sign icon-white"></i> Submit
      <% end %>
     </div>
    <% else %>
     <div class="actions inline-field span3">
      <%= button_tag(:type => 'submit', class: "btn btn-success btn-large pull-right") do %>
       <i class="icon-ok-sign icon-white"></i> Save
      <% end %>
     </div>
    <% end %>
  </div>
<% end %>

app/views/library_contacts/edit.html.erb
<div class="box-model-header"><h1>Library Contact</h1></div>   
<div class="box-model-content">
  <div class="row-fluid">
    <div class="span12 guide">
      <div class="count">
        <h3>Edit</h3>
        <div id="count" class="feed-count-empty">&#x2713;</div>
      </div>
      <%= render "shared/mini_guide" %>
    </div>
  </div>
  <div class="row-fluid">
      <div class="span12">
        <div class="addnew">
          <div>
            <%= render 'form' %>
          </div>
        </div>
      </div>
  </div>
  <div class="row-fluid">
    <div class="span12">
    </div>
  </div>
  <div class="row-fluid new-lib">
    <div class="span12 pagination-centered">
      <%= link_to 'Back', center_library_location_path(@center, @library_location) %>
    </div>
  </div>
</div>

app/views/library_contacts/index.html.erb
<h1>Listing library_contacts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Library location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @library_contacts.each do |library_contact| %>
  <tr>
    <td><%= library_contact.title %></td>
    <td><%= library_contact.phone %></td>
    <td><%= library_contact.email %></td>
    <td><%= library_contact.library_location_id %></td>
    <td><%= link_to 'Show', library_location_library_contact_path(@library_location, library_contact) %></td>
    <td><%= link_to 'Edit', edit_library_location_library_contact_path(@library_location, library_contact) %></td>
    <td><%= link_to 'Destroy', [@library_location, library_contact], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Library contact', new_library_location_library_contact_path(@library_location) %>

app/views/library_contacts/new.html.erb
<div class="box-model-header"><h1>Library Contact</h1></div>   
<div class="box-model-content">
  <div class="row-fluid">
    <div class="span12 guide">
      <div class="count">
        <h3>New</h3>
        <div id="count" class="feed-count">&#x2713;</div>
      </div>
      <%= render "shared/mini_guide" %>
    </div>
  </div>
  <div class="row-fluid">
      <div class="span12">
        <div class="addnew">
          <div>
            <%= render 'form' %>
          </div>
        </div>
      </div>
  </div>
  <div class="row-fluid">
    <div class="span12">
    </div>
  </div>
  <div class="row-fluid new-lib">
    <div class="span12 pagination-centered">
      <%= link_to 'Back', center_library_location_path(@center, @library_location) %>
    </div>
  </div>
</div>

app/views/library_contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @library_contact.title %>
</p>

<p>
  <b>Phone:</b>
  <%= @library_contact.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @library_contact.email %>
</p>

<p>
  <b>Library location:</b>
  <%= @library_contact.library_location_id %>
</p>


<%= link_to 'Back', library_location_path(@library_location) %>