config/routes.rb
Icampus::Application.routes.draw do

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :sessions
  resources :password_resets
  resources :users do
    resources :newsfeeds do
      collection { post :sort }
    end
    resources :photosfeeds do
      collection { post :sort }
    end
    resources :videosfeeds do
      collection { post :sort }
    end
    resources :eventsfeeds do
      collection { post :sort }
    end
    resource :directory
    resource :athletic
    resource :library_worldcat
    resources :centers
    resources :ios_main_icons
    resources :ios_feature_icons
    resources :ios_backgrounds
    resource :ios_topbar
    resources :android_main_icons
    resources :android_feature_icons
    resources :android_backgrounds
    resource :android_topbar
    resources :mobile_web_feature_icons
    resources :mobile_web_logos
    resource :mobile_web_topbar
    resource :apple_developer
    resource :android_profile
    resources :testers
    resource :project_info_page
    resource :support_email
    resource :cname
    resource :info_appstore
    member do
      get 'change_password'
      put 'change_password_update'
    end
    collection do
      get 'tab_feat'
      get 'tab_graph'
      get 'tab_dist'
      get 'tab_rel'
    end
  end

  resources :centers do
    resources :emergency_phones
    resources :emergency_contacts
    resources :places
    resources :library_locations do
      resources :library_hours
      resources :library_contacts
    end
  end

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :users do
      resources :centers
      member do
        get 'tab_feat'
        get 'tab_graph'
        get 'tab_dist'
        get 'tab_rel'
      end
    end
  end

  root :to => 'users#index'

end

app/models/mobile_web_logo.rb
class MobileWebLogo < ActiveRecord::Base
	belongs_to :user

	validates_presence_of :logo_size, :user_id, :logo_image
	validates_uniqueness_of :logo_size, :message => "already exists."
	attr_accessible :logo_size, :user_id, :logo_image

	has_attached_file :logo_image,
					  :url => "/assets/:user_id/:class/:attachment/:logo_size/:id/:filename",
					  :path => ":rails_root/public/assets/:user_id/:class/:attachment/:logo_size/:id/:filename"
	validates_attachment :logo_image, :presence => true, :content_type => { :content_type => "image/png" }

	Paperclip.interpolates :user_id do |attachment, style|
      attachment.instance.user.id
    end
    Paperclip.interpolates :logo_size do |attachment, style|
      attachment.instance.logo_size
    end
end

app/controllers/mobile_web_logos_controller.rb
class MobileWebLogosController < ApplicationController

  before_filter :load_user
  # GET /mobile_web_logos
  # GET /mobile_web_logos.json
  def index
    @mobile_web_logos = @user.mobile_web_logos.all
    @mobile_web_logo = @user.mobile_web_logos.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mobile_web_logos }
      format.js
    end
  end

  # GET /mobile_web_logos/1/edit
  def edit
    @mobile_web_logo = @user.mobile_web_logos.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  # POST /mobile_web_logos
  # POST /mobile_web_logos.json
  def create
    @mobile_web_logo = @user.mobile_web_logos.new(params[:mobile_web_logo])

    respond_to do |format|
      if @mobile_web_logo.save
        format.html { redirect_to user_mobile_web_logos_url, :flash => { success: "Image successfully saved." } }
        format.json { render json: @mobile_web_logo, status: :created, location: @mobile_web_logo }
        format.js
      else
        format.html do
          @mobile_web_logos = @user.mobile_web_logos.all
          render action: "index"
        end
        format.json { render json: @mobile_web_logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mobile_web_logos/1
  # PUT /mobile_web_logos/1.json
  def update
    @mobile_web_logo = @user.mobile_web_logos.find(params[:id])

    respond_to do |format|
      if @mobile_web_logo.update_attributes(params[:mobile_web_logo])
        format.html { redirect_to user_mobile_web_logos_url, :flash => { success: "Image successfully saved." } }
        format.json { head :no_content }
      else
        format.html { render action: "index" }
        format.json { render json: @mobile_web_logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mobile_web_logos/1
  # DELETE /mobile_web_logos/1.json
  def destroy
    @mobile_web_logo = @user.mobile_web_logos.find(params[:id])
    @mobile_web_logo.destroy

    respond_to do |format|
      format.html { redirect_to user_mobile_web_logos_url }
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/mobile_web_logos_helper.rb
module MobileWebLogosHelper
end

app/views/mobile_web_logos/_form.html.erb
<%= form_for([@user, @mobile_web_logo], :remote => true, :html => { :multipart => true, :class => "form-inline" }) do |f| %>
  <% if @mobile_web_logo.errors.any? %>
    <div class ="alert alert-error">
      <b><%= pluralize(@mobile_web_logo.errors.count, "error") %> caught: </b>
      <% @mobile_web_logo.errors.full_messages.each do |msg| %>
        <%= msg %>
      <% end %>
      <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
  <% end %>

  <div class="row-fluid">
    <div class="field inline-field span4 pad">
      <%= f.select :logo_size, LOGO_SIZES %>
    </div>
    <div class="field inline-field span4 pad">
      <span class="btn btn-file fileinput-button">
        <i class="icon-file icon-blue"></i>
        <span>Select...</span>
        <%= f.file_field :icon_image, :class => "file-prev" %>
      </span>
      <div class="show-prev"></div>
    </div>
    <% if @mobile_web_logo.new_record? %>
     <div class="actions inline-field span4">
      <%= button_tag(:type => 'submit', class: "btn btn-primary btn-large pull-right") do %>
       <i class="icon-plus-sign icon-white"></i> Submit
      <% end %>
     </div>
    <% else %>
     <div class="actions inline-field span4 pad">
      <%= button_tag(:type => 'submit', class: "btn btn-success") do %>
       <i class="icon-ok-sign icon-white"></i> Save
      <% end %>
     </div>
    <% end %>
  </div>
<% end %>

app/views/mobile_web_logos/_mobile_web_logo.html.erb
<%= content_tag_for :li, mobile_web_logo do %>
	<div class="row-fluid">
		<div class="span6 features-prev"><%= image_tag mobile_web_logo.logo_image.url %></div>
		<div class="span3 graph-header">
		  	<h4><%= mobile_web_logo.logo_size %></h4>
	  	</div>
	  	<div class="span3 list-controls">
	  		<div class="current-actions-wrap">
	  			<div class="current-actions">
			  	<div class="btn-group">
			  	<%= link_to raw('<i class="icon-edit"></i> Edit'), edit_user_mobile_web_logo_path(@user, mobile_web_logo), :remote => true, :class => 'btn btn-small' %>
			  	<%= link_to raw('<i class="icon-trash"></i> Delete'), [@user, mobile_web_logo], :confirm => 'Are you sure?', :method => :delete, :remote => true, :class => 'btn btn-small' %>
			  	</div>
			  	</div>
			</div>
		</div>
	</div>
	<div id="inner_<%= dom_id(mobile_web_logo) %>" class="row-fluid listItemInner"></div>
<% end %>

app/views/mobile_web_logos/create.js.erb
$('#mobileWebLogoList').prepend('<%= escape_javascript(render(@mobile_web_logo)) %>');
$('#mobileWebLogoList > li').first().effect('highlight', {color: '#e1e1ff'}, 1500);
$('#mobileWebLogo_form > form')[0].reset();
var t = parseFloat($('#count').html());
var c = t+1;
$('#count').html(c);

app/views/mobile_web_logos/destroy.js.erb
$('#<%= dom_id(@mobile_web_logo) %>').effect('highlight', {color: '#ccffd2', mode: 'hide'}, 1200);
var t = parseFloat($('#count').html());
var c = t-1;
$('#count').html(c);

app/views/mobile_web_logos/edit.html.erb
<h1>Editing mobile_web_logo</h1>

<%= render 'form' %>

<%= link_to 'Show', @mobile_web_logo %> |
<%= link_to 'Back', mobile_web_logos_path %>

app/views/mobile_web_logos/edit.js.erb
$('#inner_<%= dom_id(@mobile_web_logo) %>').html(
	'<%= escape_javascript(render "form") %></div>' +
	'<a class="kill" href="#">&times;</a>');

$('.kill', $('#inner_<%= dom_id(@mobile_web_logo) %>')).click(function() {
	$('#inner_<%= dom_id(@mobile_web_logo) %>').html("");
});

app/views/mobile_web_logos/index.html.erb
<div class="box-model-header"><h1>Mobile Web Logos</h1></div>   
<div class="box-model-content">
  <div class="row-fluid">
    <div class="span12 guide">
      <div class="count">
        <h3>Sizes</h3>
        <div id="count" class="feed-count"><%= @mobile_web_logos.count %></div>
      </div>
      <%= render "shared/mini_guide" %>
    </div>
  </div>
  <div class="row-fluid">
      <div class="span12">
        <div class="addnew">
          <div id="mobileWebLogo_form">
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  <div class="row-fluid">
    <div class="span12">
      <ul id="mobileWebLogoList" class="showList">
        <%= render @mobile_web_logos %>
      </ul>
    </div>
  </div>
</div>

app/views/mobile_web_logos/index.js.erb
$.ajax({
	success: function() {
		$('#mobileWebLogoList').html('<%= escape_javascript(render :partial => @mobile_web_logos) %>');
	}
});

app/views/mobile_web_logos/new.html.erb
<h1>New mobile_web_logo</h1>

<%= render 'form' %>

<%= link_to 'Back', mobile_web_logos_path %>

app/views/mobile_web_logos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Logo size:</b>
  <%= @mobile_web_logo.logo_size %>
</p>

<p>
  <b>User:</b>
  <%= @mobile_web_logo.user_id %>
</p>


<%= link_to 'Edit', edit_mobile_web_logo_path(@mobile_web_logo) %> |
<%= link_to 'Back', mobile_web_logos_path %>