config/routes.rb
Icampus::Application.routes.draw do

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :sessions
  resources :password_resets
  resources :users do
    resources :newsfeeds do
      collection { post :sort }
    end
    resources :photosfeeds do
      collection { post :sort }
    end
    resources :videosfeeds do
      collection { post :sort }
    end
    resources :eventsfeeds do
      collection { post :sort }
    end
    resource :directory
    resource :athletic
    resource :library_worldcat
    resources :centers
    resources :ios_main_icons
    resources :ios_feature_icons
    resources :ios_backgrounds
    resource :ios_topbar
    resources :android_main_icons
    resources :android_feature_icons
    resources :android_backgrounds
    resource :android_topbar
    resources :mobile_web_feature_icons
    resources :mobile_web_logos
    resource :mobile_web_topbar
    resource :apple_developer
    resource :android_profile
    resources :testers
    resource :project_info_page
    resource :support_email
    resource :cname
    resource :info_appstore
    member do
      get 'change_password'
      put 'change_password_update'
    end
    collection do
      get 'tab_feat'
      get 'tab_graph'
      get 'tab_dist'
      get 'tab_rel'
    end
  end

  resources :centers do
    resources :emergency_phones
    resources :emergency_contacts
    resources :places
    resources :library_locations do
      resources :library_hours
      resources :library_contacts
    end
  end

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :users do
      resources :centers
      member do
        get 'tab_feat'
        get 'tab_graph'
        get 'tab_dist'
        get 'tab_rel'
      end
    end
  end

  root :to => 'users#index'

end

app/models/emergency_contact.rb
class EmergencyContact < ActiveRecord::Base
	belongs_to :center

	attr_accessible :name, :phone, :link_url, :center_id
	validates_presence_of :name, :center_id
end

app/controllers/emergency_contacts_controller.rb
class EmergencyContactsController < ApplicationController

  before_filter :load_user_center
  # GET /emergency_contacts
  # GET /emergency_contacts.json
  def index
    @emergency_contacts = @center.emergency_contacts.all
    @emergency_contact = @center.emergency_contacts.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @emergency_contacts }
      format.js
    end
  end


  # GET /emergency_contacts/1/edit
  def edit
    @emergency_contact = @center.emergency_contacts.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  # POST /emergency_contacts
  # POST /emergency_contacts.json
  def create
    @emergency_contact = @center.emergency_contacts.new(params[:emergency_contact])

    respond_to do |format|
      if @emergency_contact.save
        format.html { redirect_to center_emergency_contacts_url, notice: 'Emergency contact was successfully created.' }
        format.json { render json: @emergency_contact, status: :created, location: center_emergency_contacts_url }
        format.js
      else
        format.html { render action: "index" }
        format.json { render json: @emergency_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /emergency_contacts/1
  # PUT /emergency_contacts/1.json
  def update
    @emergency_contact = @center.emergency_contacts.find(params[:id])

    respond_to do |format|
      if @emergency_contact.update_attributes(params[:emergency_contact])
        format.html { redirect_to center_emergency_contacts_url, notice: 'Emergency contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "index" }
        format.json { render json: @emergency_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emergency_contacts/1
  # DELETE /emergency_contacts/1.json
  def destroy
    @emergency_contact = @center.emergency_contacts.find(params[:id])
    @emergency_contact.destroy

    respond_to do |format|
      format.html { redirect_to center_emergency_contacts_url }
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/emergency_contacts_helper.rb
module EmergencyContactsHelper
end

app/views/emergency_contacts/_emergency_contact.html.erb
<%= content_tag_for :li, emergency_contact do %>
	<div class="row-fluid">
		<div class="span1"><div class="cms-icon cms-shield"></div></div>
		<div class="span8 list-left">
	  		<h4><%= emergency_contact.name %></h4>
	  		<p><%= emergency_contact.phone %> | <i><%= emergency_contact.link_url %></i></p>
	  	</div>
	  	<div class="span3 list-controls">
	  		<div class="current-actions-wrap">
	  			<div class="current-actions">
			  	<div class="btn-group">
			  	<%= link_to raw('<i class="icon-edit"></i> Edit'), edit_center_emergency_contact_path(@center, emergency_contact), :remote => true, :class => 'btn btn-small' %>
			  	<%= link_to raw('<i class="icon-trash"></i> Delete'), [@center, emergency_contact], :confirm => 'Are you sure?', :method => :delete, :remote => true, :class => 'btn btn-small' %>
			  	</div>
			  	</div>
			</div>
		</div>
	</div>
	<div id="inner_<%= dom_id(emergency_contact) %>" class="row-fluid listItemInner"></div>
<% end %>

app/views/emergency_contacts/_form.html.erb
<%= form_for([@center, @emergency_contact], :remote => true, :html => { :class => "form-inline" }) do |f| %>
  <% if @emergency_contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@emergency_contact.errors.count, "error") %> prohibited this emergency_contact from being saved:</h2>

      <ul>
      <% @emergency_contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row-fluid">
    <div class="field inline-field span3 pad">
      <%= f.text_field :name, :placeholder => "Name", :class => "fullw" %>
    </div>
    <div class="field inline-field span2 pad">
      <%= f.text_field :phone, :placeholder => "Phone", :class => "fullw" %>
    </div>
    <div class="field inline-field span4 pad">
      <%= f.text_field :link_url, :placeholder => "Link URL", :class => "fullw" %>
    </div>
    <% if @emergency_contact.new_record? %>
     <div class="actions inline-field span3">
      <%= button_tag(:type => 'submit', class: "btn btn-primary btn-large pull-right") do %>
       <i class="icon-plus-sign icon-white"></i> Submit
      <% end %>
     </div>
    <% else %>
     <div class="actions inline-field span3 pad">
      <%= button_tag(:type => 'submit', class: "btn btn-success") do %>
       <i class="icon-ok-sign icon-white"></i> Save
      <% end %>
     </div>
    <% end %>
  </div>
<% end %>

app/views/emergency_contacts/create.js.erb
$('#emcList').prepend('<%= escape_javascript(render(@emergency_contact)) %>');
$('#emcList > li').first().effect('highlight', {color: '#e1e1ff'}, 1500);
$('#emcForm > form')[0].reset();
var t = parseFloat($('#count').html());
var c = t+1;
$('#count').html(c);

app/views/emergency_contacts/destroy.js.erb
$('#<%= dom_id(@emergency_contact) %>').effect('highlight', {color: '#ccffd2', mode: 'hide'}, 1200);
var t = parseFloat($('#count').html());
var c = t-1;
$('#count').html(c);

app/views/emergency_contacts/edit.html.erb
<h1>Editing emergency_contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @emergency_contact %> |
<%= link_to 'Back', emergency_contacts_path %>

app/views/emergency_contacts/edit.js.erb
$('#inner_<%= dom_id(@emergency_contact) %>').html(
	'<%= escape_javascript(render "form") %></div>' +
	'<a class="kill" href="#">&times;</a>');

$('.kill', $('#inner_<%= dom_id(@emergency_contact) %>')).click(function() {
	$('#inner_<%= dom_id(@emergency_contact) %>').html("");
});

app/views/emergency_contacts/index.html.erb
<div class="box-model-header"><h1>Emergency</h1></div>          
  <div class="box-model-content">
    <div class="row-fluid">
      <div class="span12">
        <ul class="nav nav-tabs">
          <li class="active">
            <%= link_to raw('<h4>Emergency Contacts</h4>'), center_emergency_contacts_path %>
          </li>
          <li>
            <%= link_to raw('<h4>Emergency Phones</h4>'), center_emergency_phones_path %>
          </li>
        </ul>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12 guide">
        <div class="count">
          <h3>Contacts</h3>
          <div id="count" class="feed-count"><%= @center.emergency_contacts.count %></div>
        </div>
        <%= render "shared/mini_guide" %>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12">
        <div class="addnew">
          <div id="emcForm">
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12">
        <ul id="emcList" class="showList"><%= render @emergency_contacts %></ul>
      </div>
    </div>
  </div>
</div>

app/views/emergency_contacts/index.js.erb
$.ajax({
	success: function() {
		$('#emcList').html('<%= escape_javascript(render :partial => @emergency_contacts) %>');
	}
});

app/views/emergency_contacts/new.html.erb
<h1>New emergency_contact</h1>

<%= render 'form' %>

<%= link_to 'Back', emergency_contacts_path %>

app/views/emergency_contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @emergency_contact.name %>
</p>

<p>
  <b>Phone:</b>
  <%= @emergency_contact.phone %>
</p>

<p>
  <b>Link url:</b>
  <%= @emergency_contact.link_url %>
</p>


<%= link_to 'Edit', edit_emergency_contact_path(@emergency_contact) %> |
<%= link_to 'Back', emergency_contacts_path %>